# Generated by Django 3.1.5 on 2021-02-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210209_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
