# Generated by Django 3.1.5 on 2021-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210201_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_reason',
            field=models.CharField(choices=[('breach_of_tos', 'BREACH OF TOS'), ('general_query', 'GENERAL QUERY'), ('technical_issue', 'TECHNICAL ISSUE'), ('subscription_query', 'SUBSCRIPTION QUERY')], default='general_query', max_length=100),
        ),
    ]
