# Generated by Django 3.1.5 on 2021-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210201_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
