# Generated by Django 3.1.5 on 2021-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
