# Generated by Django 3.1.5 on 2021-02-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0005_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='SportChat',
        ),
    ]
